package com.umesh.hotelbooking.repository;

import com.umesh.hotelbooking.entity.Booking;
import com.umesh.hotelbooking.entity.BookingState;
import org.junit.jupiter.api.Test;
import org.springframework.boot.data.jpa.test.autoconfigure.DataJpaTest;
import org.springframework.dao.DataIntegrityViolationException;

import java.math.BigDecimal;
import java.time.Instant;
import java.time.LocalDate;
import java.util.Optional;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

/**
 * Proves the entity/DAO pair actually works against a real (embedded H2) database: the Long
 * primary key is generated by identity, the business uid is assigned automatically on
 * persist, and lookups happen by that uid rather than the raw Long id.
 */
@DataJpaTest
class BookingRepositoryTest {

    @org.springframework.beans.factory.annotation.Autowired
    private BookingRepository bookingRepository;

    private Booking.BookingBuilder validBuilder() {
        return Booking.builder()
                .guestId(1L)
                .propertyId(2L)
                .roomTypeId(3L)
                .checkIn(LocalDate.of(2026, 9, 10))
                .checkOut(LocalDate.of(2026, 9, 13))
                .units(1)
                .adults(2)
                .children(0)
                .totalAmount(new BigDecimal("24000.00"))
                .currency("INR")
                .holdExpiresAt(Instant.parse("2026-09-01T00:15:00Z"));
    }

    @Test
    void savingAssignsAnIdentityPrimaryKeyAndABusinessUid() {
        Booking saved = bookingRepository.save(validBuilder().build());

        assertThat(saved.getId()).isNotNull().isPositive();
        assertThat(saved.getBookingUid()).isNotBlank();
        assertThat(saved.getCreatedAt()).isNotNull();
        assertThat(saved.getState()).isEqualTo(BookingState.CREATED);
    }

    @Test
    void findByBookingUidIsWhatCallersActuallyUseToFetchData() {
        Booking saved = bookingRepository.save(validBuilder().build());

        Optional<Booking> found = bookingRepository.findByBookingUid(saved.getBookingUid());

        assertThat(found).isPresent();
        assertThat(found.get().getId()).isEqualTo(saved.getId());
    }

    @Test
    void bookingUidIsUnique() {
        Booking first = bookingRepository.saveAndFlush(validBuilder().build());
        Booking second = validBuilder().bookingUid(first.getBookingUid()).build();

        assertThatThrownBy(() -> bookingRepository.saveAndFlush(second))
                .isInstanceOf(DataIntegrityViolationException.class);
    }

    @Test
    void invalidDateRangeIsRejectedOnPersist() {
        Booking invalid = validBuilder()
                .checkIn(LocalDate.of(2026, 9, 13))
                .checkOut(LocalDate.of(2026, 9, 10))
                .build();

        assertThatThrownBy(() -> bookingRepository.saveAndFlush(invalid))
                .isInstanceOf(com.umesh.hotelbooking.exception.InvalidDateRangeException.class);
    }
}
