/**
 * JPA entities: the persisted model. Each entity carries a Long id (the database primary
 * key, generated by identity) and a separate business id (a UUID string) that is what
 * callers actually use to look the row up. The Long id never leaves this application.
 */
package com.umesh.hotelbooking.entity;
