package com.umesh.hotelbooking.domain.vo;

/**
 * Typed identifier for the client-supplied idempotency/correlation key on an API request.
 * Unlike the other typed ids, {@code MsgId} has no {@code newId()} factory: it is always
 * generated by the calling client, never by the server.
 */
public record MsgId(String value) {

    public MsgId {
        if (value == null || value.isBlank()) {
            throw new IllegalArgumentException("MsgId value must not be null or blank");
        }
    }

    public static MsgId of(String value) {
        return new MsgId(value);
    }

    @Override
    public String toString() {
        return value;
    }
}
